---
- hosts: satellite
  tasks:
  
    - name: "PING all hosts to ensure we are alive and ready"
      ping:
      
    - name: "YUM install satellite packages"
      yum: name=satellite,sos,foreman-discovery-image state=installed

    - name: "CMD install satellite"
      shell: 
        cmd: |
          satellite-installer --scenario satellite \
          --foreman-initial-organization "ExampleCom" \
          --foreman-initial-location "Irving, Tx" \
          --foreman-admin-username admin \
          --foreman-admin-password redhat \
          --foreman-proxy-dns-managed=false \
          --foreman-proxy-dhcp-managed=false
          
