
---
- hosts: nodes, satellite
  tasks:
  
    - name: "PING all hosts to ensure we are alive and ready"
      ping:

    - name: "CMD yum clean all"
      shell:                                                                                           
        cmd: |                                                                                         
          yum clean all

- hosts: satellite

    - name: "TEMPLATE install cheat-(scripts) in /var/tmp"
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0744
      with_items:
        - {src: 'cheat-sync-repos.j2',           dest: '/usr/local/bin/cheat-sync-repos.sh'}
        - {src: 'cheat-enable-repos.j2',         dest: '/usr/local/bin/cheat-enable-repos.sh'}
        - {src: 'cheat-set-policy.j2',           dest: '/usr/local/bin/cheat-set-policy.sh'}
        - {src: 'cheat-app-lifecycles.j2',       dest: '/usr/local/bin/cheat-app-lifecycles.sh'}
        - {src: 'cheat-content-views.j2',        dest: '/usr/local/bin/cheat-content-views.sh'}
