
---
- hosts: nodes, satellite
  tasks:
  
    - name: "PING all hosts to ensure we are alive and ready"
      ping:

- hosts: nodes
  tasks:

    - name: "CMD remove older katello certs"
      shell:
        cmd: |
          yum remove -y katello-ca-consumer*.noarch

    - name: "YUM install satellite crt"
      yum: name=http://satellite.example.com/pub/katello-ca-consumer-satellite.example.com-1.0-1.noarch.rpm state=installed

    - name: "CMD yum clean all"
      shell:                                                                                           
        cmd: |                                                                                         
          yum clean all

- hosts: satellite
  tasks:

    - name: "TEMPLATE install cheat-(scripts) in /var/tmp"
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0744
      with_items:
        - {src: 'cheat-sync-repos.j2',           dest: '/usr/local/bin/cheat-sync-repos.sh'}
        - {src: 'cheat-enable-repos.j2',         dest: '/usr/local/bin/cheat-enable-repos.sh'}
        - {src: 'cheat-set-policy.j2',           dest: '/usr/local/bin/cheat-set-policy.sh'}
        - {src: 'cheat-app-lifecycles.j2',       dest: '/usr/local/bin/cheat-app-lifecycles.sh'}
        - {src: 'cheat-cv-create.j2',            dest: '/usr/local/bin/cheat-cv-create.sh'}
        - {src: 'cheat-cv-publish.j2',           dest: '/usr/local/bin/cheat-cv-publish.sh'}
        - {src: 'cheat-cv-promote.j2',           dest: '/usr/local/bin/cheat-cv-promote.sh'}
        - {src: 'cheat-ak-create.j2',            dest: '/usr/local/bin/cheat-ak-create.sh'}
        - {src: 'cheat-ak-attach-subs.j2',       dest: '/usr/local/bin/cheat-ak-attach-subs.sh'}
        - {src: 'cheat-ak-autoenable.j2',        dest: '/usr/local/bin/cheat-ak-autoenable.sh'}



    - name: "CMD yum clean all"
      shell:                                                                                           
        cmd: |                                                                                         
          yum clean all
