---
- hosts: satellite
  tasks:
  
    - name: "PING all hosts to ensure we are alive and ready"
      ping:

    - name: "CMD cleanup previous satellite storage"
      shell: 
        cmd: |
          echo "need to check mounts && umount"
          vgs sat6_vg && vgremove --force sat6_vg
          pvs /dev/vdb && pvremove --force /dev/vdb
          wipefs -a /dev/vdb
          
    - name: "CMD prepare previous satellite storage"
      shell: 
        cmd: |
          pvcreate /dev/vdb
          vgcreate sat6_vg /dev/vdb
          lvcreate -L 50GB  -n mongodb sat_vg
          lvcreate -L 100GB -n pulp    sat_vg
          lvcreate -L 5GB   -n pgsql   sat_vg
          lvcreate -L 5GB   -n squid   sat_vg
          lvcreate -L 20GB  -n cache   sat_vg

    - name: "CMD remove old cache directory (eventually)"
      shell: 
        cmd: |
          mv /var/cache /var/cache.old

    - name: "CMD create filesystems, mount points and fstab entries"
      shell: 
        cmd: |
          mkfs -t fs /dev/{{ item.vg }}/{{ item.lv }}
          mkdir -p {{ item.mount }}
          grep -q {{ item.mount }} /etc/fstab || echo "/dev/mapper/{{item.vg}}-{{ item.lv }} {{ item.mount }} xfs defaults 0 0" >> /etc/fstab
      with_items
        - {vg:'sat6_vg', lv:'pulp',    mount:'/var/lib/pulp'} 
        - {vg:'sat6_vg', lv:'pgsql',   mount:'/var/lib/pgsql'} 
        - {vg:'sat6_vg', lv:'mongodb', mount:'/var/libm/mongodb'} 
        - {vg:'sat6_vg', lv:'squid',   mount:'/var/spool/squid'} 
        - {vg:'sat6_vg', lv:'cache',   mount:'/var/cache'} 
        
    - name: "CMD mount everything"
      shell: 
        cmd: |
          mount -a
